"""由 data/*.yaml 生成中英双语的 README 与 docs/ 视图（默认英文，中文为 *.zh-CN.md）。

用法：
  python scripts/render.py          # 校验并生成
  python scripts/render.py --check  # 只校验，并检查生成结果是否已提交（CI 用）
"""
import argparse
import sys
from datetime import date, timedelta

from lib import ROOT, load_meta, load_projects, validate

STALE_DAYS = 365
RING_ORDER = ("adopt", "trial", "assess", "hold")

# 界面文案：en 为默认，zh 为中文
T = {
    "en": {
        "suffix": "", "switch": "[简体中文](README.zh-CN.md)", "switch_doc": "[简体中文]({name}.zh-CN.md)",
        "generated": "<!-- Generated by scripts/render.py. Edit data/*.yaml instead of this file. -->",
        "intro": "Curated frontier technologies, engineering practices and tools that Origen follows. "
                 "Each entry says **why we care about it**, and a technology radar ring marks our stance.",
        "total": "**{n}** projects:", "by_radar": "🎯 By radar",
        "kind": "Kind", "radar": "Radar", "toc": "Contents",
        "cols": ["Project", "Category", "Kind", "Radar", "Why we care", "⭐", "Last push"],
        "archived": " ⚠️archived", "missing": " ❌gone", "stale": " 💤stale 1y+",
        "contrib_h": "Contributing",
        "contrib": "See [CONTRIBUTING.md](CONTRIBUTING.md). The easiest way: open an issue with the **Recommend a project** "
                   "template and paste GitHub links, or run `/curate add <url>` in Claude Code inside this repo.",
        "back": "[← Back to overview](../README.md)", "radar_title": "🎯 Technology Radar",
    },
    "zh": {
        "suffix": ".zh-CN", "switch": "[English](README.md)", "switch_doc": "[English]({name}.md)",
        "generated": "<!-- 本文件由 scripts/render.py 自动生成，请修改 data/*.yaml，不要直接编辑 -->",
        "intro": "Origen 关注的前沿技术、工程实践与工具精选。每一项都写明了**我们为什么关注它**，并用技术雷达标注团队态度。",
        "total": "共 **{n}** 个项目：", "by_radar": "🎯 按雷达查看",
        "kind": "类型", "radar": "雷达", "toc": "目录",
        "cols": ["项目", "分类", "类型", "雷达", "为什么关注", "⭐", "最近推送"],
        "archived": " ⚠️已归档", "missing": " ❌失效", "stale": " 💤一年未更新",
        "contrib_h": "贡献",
        "contrib": "见 [CONTRIBUTING.zh-CN.md](CONTRIBUTING.zh-CN.md)。最简单的方式：用 **推荐项目 / Recommend a project** "
                   "模板新建 issue 并贴上 GitHub 链接，或者在本仓库中使用 Claude Code 的 `/curate add <url>`。",
        "back": "[← 返回总览](../README.zh-CN.md)", "radar_title": "🎯 技术雷达",
    },
}


def tr(obj, field, lang):
    """取对象的某个字段；中文优先取 field_zh，缺失时回退到英文。"""
    return (obj.get(f"{field}_zh") or obj[field]) if lang == "zh" else obj[field]


def fmt_stars(n):
    if n is None:
        return "-"
    return f"{n / 1000:.1f}k" if n >= 1000 else str(n)


def row(p, meta, lang, show_category):
    t = T[lang]
    flags = ""
    if p.get("archived"):
        flags += t["archived"]
    if p.get("missing"):
        flags += t["missing"]
    elif p.get("pushed_at") and date.fromisoformat(p["pushed_at"]) < date.today() - timedelta(days=STALE_DAYS):
        flags += t["stale"]
    kind = meta["kinds"][p["kind"]]
    cells = [f"[{p['repo']}](https://github.com/{p['repo']}){flags}"]
    if show_category:
        top, sub = meta["index"][p["category"]]
        cells.append(f"{tr(top, 'name', lang)} / {tr(sub, 'name', lang)}")
    cells += [f"{kind['emoji']} {tr(kind, 'name', lang)}", tr(meta["rings"][p["ring"]], "name", lang),
              tr(p, "why", lang), fmt_stars(p.get("stars")), p.get("pushed_at") or "-"]
    return "| " + " | ".join(str(c).replace("|", "\\|") for c in cells) + " |"


def sort_key(p):
    return (RING_ORDER.index(p["ring"]), -(p.get("stars") or 0))


def table(items, meta, lang, show_category=False):
    head = [c for i, c in enumerate(T[lang]["cols"]) if show_category or i != 1]
    out = ["| " + " | ".join(head) + " |", "|" + "---|" * len(head)]
    out += [row(p, meta, lang, show_category) for p in sorted(items, key=sort_key)]
    return "\n".join(out)


def legend(meta, lang):
    t = T[lang]
    kinds = " · ".join(f"{k['emoji']} **{tr(k, 'name', lang)}**: {tr(k, 'desc', lang)}" for k in meta["kinds"].values())
    rings = " · ".join(f"**{tr(r, 'name', lang)}** ({rid}): {tr(r, 'desc', lang)}" for rid, r in meta["rings"].items())
    return f"- {t['kind']}: {kinds}\n- {t['radar']}: {rings}"


def render_readme(projects, meta, lang):
    t, sfx = T[lang], T[lang]["suffix"]
    by_cat = {}
    for p in projects:
        by_cat.setdefault(p["category"], []).append(p)
    counts = {k: sum(p["kind"] == k for p in projects) for k in meta["kinds"]}

    out = [
        t["generated"], "# Awesome Origen", "", t["switch"], "", t["intro"], "",
        t["total"].format(n=len(projects)) + " " + " · ".join(
            f"[{meta['kinds'][k]['emoji']} {tr(meta['kinds'][k], 'name', lang)} {n}](docs/{k}{sfx}.md)" for k, n in counts.items()
        ) + f" · [{t['by_radar']}](docs/radar{sfx}.md)",
        "", legend(meta, lang), "", f"## {t['toc']}", "",
    ]
    for top in meta["categories"]:
        n = sum(len(by_cat.get(f"{top['id']}/{s['id']}", [])) for s in top["children"])
        out.append(f"- [{tr(top, 'name', lang)}](#{top['id']}) ({n}) — {tr(top, 'desc', lang)}")
    for top in meta["categories"]:
        out += ["", f'<a id="{top["id"]}"></a>', "", f"## {tr(top, 'name', lang)}", "", f"> {tr(top, 'desc', lang)}"]
        for sub in top["children"]:
            items = by_cat.get(f"{top['id']}/{sub['id']}")
            if items:
                out += ["", f"### {tr(sub, 'name', lang)}", "", table(items, meta, lang)]
    out += ["", f"## {t['contrib_h']}", "", t["contrib"], ""]
    return "\n".join(out)


def render_view(title, name, groups, meta, lang):
    t = T[lang]
    out = [t["generated"], f"# {title}", "", f"{t['back']} · {t['switch_doc'].format(name=name)}", ""]
    for heading, items in groups:
        if items:
            out += [f"## {heading} ({len(items)})", "", table(items, meta, lang, show_category=True), ""]
    return "\n".join(out)


def outputs(projects, meta):
    files = {}
    for lang in T:
        sfx = T[lang]["suffix"]
        files[ROOT / f"README{sfx}.md"] = render_readme(projects, meta, lang)
        for kid, k in meta["kinds"].items():
            groups = [(tr(r, "name", lang), [p for p in projects if p["kind"] == kid and p["ring"] == rid])
                      for rid, r in meta["rings"].items()]
            files[ROOT / "docs" / f"{kid}{sfx}.md"] = render_view(
                f"{k['emoji']} {tr(k, 'name', lang)}: {tr(k, 'desc', lang)}", kid, groups, meta, lang)
        groups = [(f"{tr(r, 'name', lang)} ({rid}) — {tr(r, 'desc', lang)}", [p for p in projects if p["ring"] == rid])
                  for rid, r in meta["rings"].items()]
        files[ROOT / "docs" / f"radar{sfx}.md"] = render_view(T[lang]["radar_title"], "radar", groups, meta, lang)
    return files


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    meta, projects = load_meta(), load_projects()
    errors = validate(projects, meta)
    if errors:
        print("数据校验失败：\n  " + "\n  ".join(errors), file=sys.stderr)
        sys.exit(1)

    stale = []
    for path, content in outputs(projects, meta).items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                stale.append(path.relative_to(ROOT).as_posix())
        else:
            path.parent.mkdir(exist_ok=True)
            path.write_text(content, encoding="utf-8", newline="\n")
    if stale:
        print(f"以下文件与数据不一致，请运行 python scripts/render.py 后提交：{stale}", file=sys.stderr)
        sys.exit(1)
    print(f"OK：{len(projects)} 个项目")


if __name__ == "__main__":
    main()
